apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: croa-api
  name: croa-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: croa-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: croa-api
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        image: croa-api
        imagePullPolicy: ""
        name: croa-api
        ports:
        - containerPort: 8090
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
