apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: croa-api
  name: croa-api
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
  selector:
    service: croa-api
status:
  loadBalancer: {}
