apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grafana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: grafana
    spec:
      containers:
      - image: grafana/grafana
        imagePullPolicy: ""
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
