apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: grafana
  name: grafana
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: grafana
status:
  loadBalancer: {}
