apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: graylog
  name: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      service: graylog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: graylog
    spec:
      containers:
      - env:
        - name: GRAYLOG_ELASTICSEARCH_VERSION
          value: "7"
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://localhost:9000/
        image: graylog/graylog:4.1.1
        imagePullPolicy: ""
        name: graylog
        ports:
        - containerPort: 9000
        - containerPort: 1514
        - containerPort: 1514
          protocol: UDP
        - containerPort: 12201
        - containerPort: 12201
          protocol: UDP
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
