apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: graylog
  name: graylog
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "1514"
    port: 1514
    targetPort: 1514
  - name: 1514-udp
    port: 1514
    protocol: UDP
    targetPort: 1514
  - name: "12201"
    port: 12201
    targetPort: 12201
  - name: 12201-udp
    port: 12201
    protocol: UDP
    targetPort: 12201
  - name: "5555"
    port: 5555
    targetPort: 5555
  selector:
    service: graylog
status:
  loadBalancer: {}
