apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: keycloack
  name: keycloack
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8080
  selector:
    service: keycloack
status:
  loadBalancer: {}
