apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: keycloack
  name: keycloack
spec:
  replicas: 1
  selector:
    matchLabels:
      service: keycloack
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: keycloack
    spec:
      containers:
      - env:
        - name: DB_VENDOR
          value: h2
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KEYCLOAK_USER
          value: admin
        image: quay.io/keycloak/keycloak
        imagePullPolicy: ""
        name: keycloack
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
