apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloack
  name: keycloack
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8080
  selector:
    io.kompose.service: keycloack
status:
  loadBalancer: {}
