apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: loki
  name: loki
spec:
  ports:
  - name: "3100"
    port: 3100
    targetPort: 3100
  selector:
    service: loki
status:
  loadBalancer: {}
