apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      service: loki
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: loki
    spec:
      containers:
      - args:
        - -config.file=/etc/loki/local-config.yaml
        image: grafana/loki
        imagePullPolicy: ""
        name: loki
        ports:
        - containerPort: 3100
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
