apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongo-express
  name: mongo-express
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    service: mongo-express
status:
  loadBalancer: {}
