apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongo-api
  name: mongo-api
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: mongo-api
status:
  loadBalancer: {}
