apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mongo-api
  name: mongo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongo-api
    spec:
      containers:
      - image: mongo:4.2
        imagePullPolicy: ""
        name: mongo-api
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
