apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongo
    spec:
      containers:
      - image: mongo:4.2
        imagePullPolicy: ""
        name: mongo
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
