apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo-express
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongo-express
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo-api
        image: mongo-express
        imagePullPolicy: ""
        name: mongo-express
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
