apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: portainer
  name: portainer
spec:
  ports:
  - name: "10000"
    port: 10000
    targetPort: 9000
  selector:
    service: portainer
status:
  loadBalancer: {}
