apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: portainer
  name: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: portainer
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: portainer
    spec:
      containers:
      - image: portainer/portainer-ce:latest
        imagePullPolicy: ""
        name: portainer
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: portainer-claim0
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: portainer-claim0
        persistentVolumeClaim:
          claimName: portainer-claim0
          readOnly: true
status: {}
