apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      service: prometheus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: prometheus
    spec:
      containers:
      - args:
        - --web.enable-lifecycle
        - --config.file=/etc/prometheus/prometheus.yml
        image: prom/prometheus
        imagePullPolicy: ""
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
