apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: promtail
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/config.yml
        image: grafana/promtail
        imagePullPolicy: ""
        name: promtail
        resources: {}
        volumeMounts:
        - mountPath: /var/log
          name: promtail-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: promtail-claim0
        persistentVolumeClaim:
          claimName: promtail-claim0
status: {}
