apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: prometheus
  name: prometheus
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: prometheus
status:
  loadBalancer: {}
