apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        imagePullPolicy: ""
        name: rabbitmq
        ports:
        - containerPort: 15672
        - containerPort: 5672
        - containerPort: 15692
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
