global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: rabbitmq
    static_configs:
      - targets:
          - rabbitmq:15692

  - job_name: croa-app
    metrics_path: /api/croa/actuator/prometheus
    static_configs:
      - targets:
          - client-api:8090